#! /bin/sh
lxpolkit &
xrdb -merge ~/.Xresources
picom &
nitrogen --restore
xsetroot -cursor_name left_ptr &
numlockx &
sxhkd &
kdeconnect-cli -l &
$HOME/.config/polybar/launch.sh
firefox &
telegram-desktop &
thunderbird &
keepassxc &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         3
bspc config window_gap           3

bspc config split_ratio          0.52

bspc config borderless_monocle   true
bspc config single_monocle true
bspc config gapless_monocle      true

bspc config normal_border_color "#b6a5a7"
bspc config active_border_color "#c6a0f6"
bspc config focused_border_color "#c6a0f6"

bspc rule -a firefox desktop='^1'
bspc rule -a TelegramDesktop desktop='^2'
bspc rule -a thunderbird desktop='^7'
bspc rule -a KeePassXC desktop='^8'
